export const servicesInfo = [
  {
    id: 1,
    title: "Standard Cleaning",
    img: "https://sparklingclean.siterubix.com/wp-content/uploads/2023/09/1-8.png",
    desc: "The standard cleaning is our most popular package. Keep your home neat & tidy.",
  },
  {
    id: 2,
    title: "Deep Cleaning",
    img: "https://sparklingclean.siterubix.com/wp-content/uploads/2023/09/2-3.png",
    desc: "The deep clean is for busy homeowners who want their to-do list empty & house spotless.",
  },
  {
    id: 3,
    title: "Move In/Move Out Cleaning",
    img: "https://sparklingclean.siterubix.com/wp-content/uploads/2023/09/Untitled-720-%C3%97-600-px-1-1.png",
    desc: "The move-in/move-out cleaning will have your new or old home spotless and ready for moving day.",
  },
  {
    id: 4,
    title: "Post Construction Cleanup",
    img: "https://sparklingclean.siterubix.com/wp-content/uploads/2023/09/Untitled-design-55-1.png",
    desc: "Providing thorough and efficient cleaning solutions after construction projects, removing debris, dust, and ensuring a safe and pristine environment, leaving your site spotless and ready for use.",
  },
];

export const KitchenCleaningData = [
  { id: 1, task: 'Clean cobwebs from lights, sills', standardClean: true, deepClean: true, moveInOut: true },
  { id: 2, task: 'Clean countertops', standardClean: true, deepClean: true, moveInOut: true },
  { id: 3, task: 'Dust all lights, ceiling fans & blades', standardClean: true, deepClean: true, moveInOut: true },
  { id: 4, task: 'Take out the trash', standardClean: true, deepClean: true, moveInOut: true },
  { id: 5, task: 'Clean table & chairs', standardClean: true, deepClean: true, moveInOut: true },
  { id: 6, task: 'Clean inside and outside of microwave', standardClean: true, deepClean: true, moveInOut: true },
  { id: 7, task: 'Clean stove burners; clean stovetop, front & control panels', standardClean: true, deepClean: true, moveInOut: true },
  { id: 8, task: 'Clean & dry sink counters & soap dish', standardClean: true, deepClean: true, moveInOut: true },
  { id: 9, task: 'Sweep & mop floors', standardClean: true, deepClean: true, moveInOut: true },
  { id: 10, task: 'Clean counters & backsplash', standardClean: true, deepClean: true, moveInOut: true },
  { id: 11, task: 'Clean front of all cabinets', standardClean: false, deepClean: true, moveInOut: true },
  { id: 12, task: 'Clean oven hood vent', standardClean: false, deepClean: true, moveInOut: true },
  { id: 13, task: 'Window ledges', standardClean: false, deepClean: true, moveInOut: true },
  { id: 14, task: 'Doors & door frames dusted', standardClean: false, deepClean: true, moveInOut: true },
  { id: 15, task: 'Baseboards dusted', standardClean: false, deepClean: true, moveInOut: true },
  { id: 16, task: 'Dust & disinfect light switches and door knobs', standardClean: false, deepClean: true, moveInOut: true },
  { id: 17, task: 'Baseboards wiped down', standardClean: false, deepClean: true, moveInOut: true },
  { id: 18, task: 'Clean top of the fridge', standardClean: false, deepClean: true, moveInOut: true },
  { id: 19, task: 'Sweep pantry floor and wipe down shelves', standardClean: false, deepClean: false, moveInOut: true },
  { id: 20, task: 'Doors and door frames wiped down', standardClean: false, deepClean: false, moveInOut: true },
  { id: 21, task: 'Blinds and shutters wet wiped down', standardClean: false, deepClean: false, moveInOut: true },
];

export const BathroomCleaningData = [
  { id: 1, task: 'Clean all cobwebs & dust shelves', standardClean: true, deepClean: true, moveInOut: true },
  { id: 2, task: 'Clean, buff all mirrors & glass', standardClean: true, deepClean: true, moveInOut: true },
  { id: 3, task: 'Clean counter tops & backsplash', standardClean: true, deepClean: true, moveInOut: true },
  { id: 4, task: 'Dust all light fixtures & clean sink(s)', standardClean: true, deepClean: true, moveInOut: true },
  { id: 5, task: 'Clean & dry shower door, track & glass', standardClean: true, deepClean: true, moveInOut: true },
  { id: 6, task: 'Clean & dry sink', standardClean: true, deepClean: true, moveInOut: true },
  { id: 7, task: 'Clean inside & outside of the toilet', standardClean: true, deepClean: true, moveInOut: true },
  { id: 8, task: 'Empty garbage', standardClean: true, deepClean: true, moveInOut: true },
  { id: 9, task: 'Sweep/vacuum & mop floors', standardClean: true, deepClean: true, moveInOut: true },
  { id: 10, task: 'Cabinet fronts cleaned', standardClean: false, deepClean: true, moveInOut: true },
  { id: 11, task: 'Window ledges', standardClean: false, deepClean: true, moveInOut: true },
  { id: 12, task: 'Doors, frames dusted & wiped down', standardClean: false, deepClean: true, moveInOut: true },
  { id: 13, task: 'Dust & wipe down baseboards', standardClean: false, deepClean: true, moveInOut: true },
  { id: 14, task: 'Dust & wipe blinds', standardClean: false, deepClean: false, moveInOut: true },
];
export const BedroomAndCommonAreaCleaningData = [
  { id: 1, task: 'Clean all cobwebs & dust shelves', standardClean: true, deepClean: true, moveInOut: true },
  { id: 2, task: 'Clean, buff all mirrors & glass', standardClean: true, deepClean: true, moveInOut: true },
  { id: 3, task: 'Clean counter tops & backsplash', standardClean: true, deepClean: true, moveInOut: true },
  { id: 4, task: 'Dust all light fixtures & clean sink(s)', standardClean: true, deepClean: true, moveInOut: true },
  { id: 5, task: 'Clean & dry shower door, track & glass', standardClean: true, deepClean: true, moveInOut: true },
  { id: 6, task: 'Clean & dry sink', standardClean: true, deepClean: true, moveInOut: true },
  { id: 7, task: 'Clean inside & outside of the toilet', standardClean: true, deepClean: true, moveInOut: true },
  { id: 8, task: 'Empty garbage', standardClean: true, deepClean: true, moveInOut: true },
  { id: 9, task: 'Sweep/vacuum & mop floors', standardClean: true, deepClean: true, moveInOut: true },
  { id: 10, task: 'Cabinet fronts cleaned', standardClean: false, deepClean: true, moveInOut: true },
  { id: 11, task: 'Window ledges', standardClean: false, deepClean: true, moveInOut: true },
  { id: 12, task: 'Doors, frames dusted & wiped down', standardClean: false, deepClean: true, moveInOut: true },
  { id: 13, task: 'Dust & wipe down baseboards', standardClean: false, deepClean: true, moveInOut: true },
  { id: 14, task: 'Dust & wipe blinds', standardClean: false, deepClean: false, moveInOut: true },
  
];